# Generated by Django 5.0 on 2024-06-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='imię')),
                ('last_name', models.CharField(max_length=150, verbose_name='nazwisko')),
                ('about', models.TextField(blank=True, verbose_name='opis')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='zdjęcie')),
            ],
            options={
                'verbose_name': 'reżyser',
                'verbose_name_plural': 'reżyserzy',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'verbose_name': 'film', 'verbose_name_plural': 'filmy'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='published_at',
            field=models.DateTimeField(verbose_name='data premiery'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(verbose_name='ocena'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='short_description',
            field=models.TextField(verbose_name='krótki opis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='tytuł'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.director', verbose_name='reżyser'),
        ),
    ]
